# Generated by Django 5.0.4 on 2024-05-18 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("company_name", models.TextField(default="Company", max_length=150)),
                (
                    "password",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "password_confirmation",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "logo",
                    models.ImageField(default="default2.jpg", upload_to="company_pics"),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("Backend", "Backend"),
                            ("Frontend", "Frontend"),
                            ("Full-stack", "Full-stack"),
                            ("Data-science", "Data-science"),
                            ("Data-engineering", "Data-engineering"),
                            ("Devops", "Devops"),
                            ("Mobile", "Mobile"),
                            ("UI/UX", "UI/UX"),
                            ("Marketing", "Marketing"),
                            ("SEO", "SEO"),
                            ("SEM", "SEM"),
                            ("PPC", "PPC"),
                            ("Finance", "Finance"),
                            ("Accounting", "Accounting"),
                            ("Audit", "Audit"),
                            ("HR", "HR"),
                            ("Recruiting", "Recruiting"),
                            ("Hiring", "Hiring"),
                            ("Recruitment", "Recruitment"),
                            ("Sales", "Sales"),
                            ("Digital Marketing", "Digital Marketing"),
                            ("Other", "Other"),
                        ],
                        max_length=200,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "number_of_employees",
                    models.CharField(
                        choices=[
                            ("1-10", "1-10"),
                            ("11-50", "11-50"),
                            ("51-100", "51-100"),
                            ("100-1000", "100-1000"),
                            ("1000+", "1000+"),
                        ],
                        max_length=200,
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=255)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("Employee", "Employee"), ("Company", "Company")],
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("crated_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Companies Profile",
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(max_length=50, unique=True)),
                ("first_name", models.TextField(max_length=50)),
                ("last_name", models.TextField(max_length=50)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "password",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "password_confirmation",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                ("job_title", models.CharField(max_length=200)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("Junior", "Junior"),
                            ("Mid Level", "Mid Level"),
                            ("Senior Level", "Senior Level"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=200
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("Employee", "Employee"), ("Company", "Company")],
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
